# Generated by Django 4.1.5 on 2023-01-29 05:41
from django.core.management import call_command
from django.db import migrations


def loadfixture(app, scema_editor):
    call_command("loaddata", "models/fixtures/school.json")


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [migrations.RunPython(loadfixture)]
