# Generated by Django 4.1.5 on 2023-01-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_likepost_likecomment"),
        ("models", "0003_auto_20230129_1206"),
    ]

    operations = []
